spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming
    username: streaming_user
    password: streaming_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: streamManager@gmail.com
    password: streamManager
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true